/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 18-Sep-2020 12:06:03
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2019a\extern\include\tmwtypes.h 
 */
const int BL = 101;
const int16_T B[101] = {
        0,     -1,      1,     -2,     -6,      1,     -8,    -15,      0,
      -19,    -26,      3,    -31,    -33,     18,    -37,    -24,     59,
      -29,     13,    134,     -4,     82,    236,     20,    165,    339,
        5,    226,    392,   -106,    220,    339,   -373,    110,    141,
     -834,    -98,   -205,  -1498,   -329,   -645,  -2360,   -395,  -1085,
    -3545,    219,  -1409,  -6602,   6843,  20316,   6843,  -6602,  -1409,
      219,  -3545,  -1085,   -395,  -2360,   -645,   -329,  -1498,   -205,
      -98,   -834,    141,    110,   -373,    339,    220,   -106,    392,
      226,      5,    339,    165,     20,    236,     82,     -4,    134,
       13,    -29,     59,    -24,    -37,     18,    -33,    -31,      3,
      -26,    -19,      0,    -15,     -8,      1,     -6,     -2,      1,
       -1,      0
};
