/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 11-Sep-2020 10:20:40
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s34,32 -> [-2 2)  (auto determined)
 *   Product         : s31,32 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s34,32 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2019a\extern\include\tmwtypes.h 
 */
const int BL = 101;
const int32_T B[101] = {
             0,         -21,         -48,         -72,         -85,         -79,
           -51,          -7,          41,          73,          68,          10,
          -105,        -266,        -445,        -602,        -698,        -700,
          -600,        -420,        -209,         -40,          11,        -113,
          -434,        -921,       -1492,       -2024,       -2386,       -2466,
         -2212,       -1658,        -922,        -199,         284,         321,
          -214,       -1320,       -2844,       -4489,       -5858,       -6533,
         -6157,       -4522,       -1632,        2271,        6737,       11167,
         14924,       17439,       18324,       17439,       14924,       11167,
          6737,        2271,       -1632,       -4522,       -6157,       -6533,
         -5858,       -4489,       -2844,       -1320,        -214,         321,
           284,        -199,        -922,       -1658,       -2212,       -2466,
         -2386,       -2024,       -1492,        -921,        -434,        -113,
            11,         -40,        -209,        -420,        -600,        -700,
          -698,        -602,        -445,        -266,        -105,          10,
            68,          73,          41,          -7,         -51,         -79,
           -85,         -72,         -48,         -21,           0
};
